CREATE TABLE MEMBER(
	MPK VARCHAR(20) PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	SCORE VARCHAR(20) NOT NULL
);

INSERT INTO MEMBER VALUES((SELECT NVL(MAX(MPK),0)+1 FROM MEMBER),'아무무','78');
INSERT INTO MEMBER VALUES((SELECT NVL(MAX(MPK),0)+1 FROM MEMBER),'아리','93');

SELECT * FROM USER_TABLES;
SELECT * FROM MEMBER;

DROP TABLE MEMBER;