CREATE TABLE MEMBER(
	MID VARCHAR(10) PRIMARY KEY,
	MPW VARCHAR(10) NOT NULL,
	MNAME VARCHAR(20) NOT NULL
);
CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	MID VARCHAR(10) NOT NULL, -- FK는 반드시 상대 테이블의 PK를 사용
	MSG VARCHAR(50) NOT NULL,
	FAVCNT INT DEFAULT 0,
	RCNT INT DEFAULT 0
);
CREATE TABLE REPLY(
	RID INT PRIMARY KEY,
	MID VARCHAR(10) NOT NULL,
	BID INT NOT NULL,
	RMSG VARCHAR(30) NOT NULL,
	CONSTRAINT BOARD_REPLY FOREIGN KEY (BID) REFERENCES BOARD (BID) ON DELETE CASCADE
);

WHERE TITLE LIKE '%'||?||'%'

SELECT * FROM USER_TABLES;

SELECT * FROM BOARD;

DELETE FROM BOARD WHERE BID='2';

SELECT * FROM (SELECT BID,MNAME,MSG,FAVCNT,RCNT FROM BOARD JOIN MEMBER ON BOARD.MID = MEMBER.MID WHERE MNAME LIKE '%'||'티'||'%' ORDER BY BID DESC) WHERE ROWNUM <=2;

SELECT BID,MNAME,MSG,FAVCNT,RCNT FROM BOARD JOIN MEMBER ON BOARD.MID = MEMBER.MID
WHERE MEMBER.MID='timo' ORDER BY BID DESC;

SELECT BID,MNAME,MSG,FAVCNT,RCNT FROM BOARD JOIN MEMBER ON BOARD.MID = MEMBER.MID WHERE MNAME LIKE '%'||'티'||'%' ORDER BY BID DESC;
SELECT RID,MNAME,BID,RMSG FROM REPLY JOIN MEMBER ON REPLY.MID = MEMBER.MID ORDER BY RID DESC;